name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *'  # Run every hour
  workflow_dispatch: # Allow manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Go dependencies
        run: go get ./...

      - name: Run Go script to generate README.md
        run: go run main.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config user.name Adnan Gulegulzar
          git config user.email 32373065+ADorigi@users.noreply.github.com.
          git add README.md
          git commit -m 'Update profile README with active repos'
          git push
